# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, vars, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/vg--system-root";
      fsType = "btrfs";
      options = [
	      "subvol=@"
        "compress=zstd:1"
        "noatime"
        "ssd"
      ];
    };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5A63-E7F1";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/nix" =
    { device = "/dev/mapper/vg--system-nix";
      fsType = "btrfs";
      options = [
	      "subvol=@nix"
        "compress=zstd:1"
        "noatime"
        "ssd"
      ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/vg--system-log";
      fsType = "btrfs";
      options = [
	      "subvol=@log"
        "compress=zstd:3"
        "noatime"
        "ssd"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/vg--home-home";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "compress=zstd:1"
        "noatime"
        "ssd"
        "space_cache=v2"
      ];
    };

  fileSystems."/home/${vars.user}/games" =
    { device = "/dev/mapper/vg--home-home";
      fsType = "btrfs";
      options = [
        "subvol=@games"
        "compress=zstd:1"
        "noatime"
        "ssd"
      ];
      neededForBoot = false;
    };

  fileSystems."/home/${vars.user}/Documents" =
    { device = "/dev/mapper/vg--home-home";
      fsType = "btrfs";
      options = [
        "subvol=@Documents"
        "compress=zstd:3"
        "noatime"
        "ssd"
      ];
      neededForBoot = false;
    };

  swapDevices = [{ device = "/dev/disk/by-uuid/ef2296c9-8615-4d43-88cf-cd82171ec49b"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
